// Code generated by MockGen. DO NOT EDIT.
// Source: sm/smbroker (interfaces: BrokerI)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	smbroker "sm/smbroker"

	gomock "github.com/golang/mock/gomock"
)

// MockBrokerI is a mock of BrokerI interface.
type MockBrokerI struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerIMockRecorder
}

// MockBrokerIMockRecorder is the mock recorder for MockBrokerI.
type MockBrokerIMockRecorder struct {
	mock *MockBrokerI
}

// NewMockBrokerI creates a new mock instance.
func NewMockBrokerI(ctrl *gomock.Controller) *MockBrokerI {
	mock := &MockBrokerI{ctrl: ctrl}
	mock.recorder = &MockBrokerIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerI) EXPECT() *MockBrokerIMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockBrokerI) Broadcast(arg0 context.Context, arg1 smbroker.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockBrokerIMockRecorder) Broadcast(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockBrokerI)(nil).Broadcast), arg0, arg1)
}

// GetServices mocks base method.
func (m *MockBrokerI) GetServices(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServices indicates an expected call of GetServices.
func (mr *MockBrokerIMockRecorder) GetServices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockBrokerI)(nil).GetServices), arg0)
}

// Register mocks base method.
func (m *MockBrokerI) Register(arg0 context.Context, arg1 string) (chan smbroker.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1)
	ret0, _ := ret[0].(chan smbroker.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockBrokerIMockRecorder) Register(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBrokerI)(nil).Register), arg0, arg1)
}

// Response mocks base method.
func (m *MockBrokerI) Response(arg0 context.Context, arg1 string, arg2 smbroker.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Response indicates an expected call of Response.
func (mr *MockBrokerIMockRecorder) Response(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockBrokerI)(nil).Response), arg0, arg1, arg2)
}

// Send mocks base method.
func (m *MockBrokerI) Send(arg0 context.Context, arg1 string, arg2 smbroker.Message) (chan smbroker.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(chan smbroker.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockBrokerIMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBrokerI)(nil).Send), arg0, arg1, arg2)
}
